#!/usr/bin/env node
// Writes a review sheet for one language: every string with its German source.
//   node scripts/i18n-review.mjs ar   ->  docs/i18n-review/ar.md
import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';

const lang = process.argv[2];
if (!lang) {
  console.error('Usage: node scripts/i18n-review.mjs <lang>');
  process.exit(1);
}

const root = join(import.meta.dirname, '..');
const load = (code) =>
  JSON.parse(readFileSync(join(root, 'src/i18n/locales', `${code}.json`), 'utf8'));

function flatten(obj, prefix = '') {
  return Object.entries(obj).flatMap(([k, v]) => {
    const key = prefix ? `${prefix}.${k}` : k;
    return v && typeof v === 'object' ? flatten(v, key) : [[key, v]];
  });
}

const de = Object.fromEntries(flatten(load('de')));
const target = flatten(load(lang));
const cell = (s) => String(s).replaceAll('|', '\\|');

const lines = [
  `# Translation review: ${lang}`,
  '',
  `Generated by \`node scripts/i18n-review.mjs ${lang}\` from \`src/i18n/locales/${lang}.json\`. Write corrections in the last column (regenerating overwrites this file), or edit the JSON file directly.`,
  '',
  'Placeholders like `{{email}}` must stay unchanged. "CleanSpot" is the product name and is not translated.',
  '',
  `| # | Key | Deutsch (source) | ${lang} | OK / correction |`,
  '| --- | --- | --- | --- | --- |',
  ...target.map(
    ([key, value], i) => `| ${i + 1} | \`${key}\` | ${cell(de[key] ?? '')} | ${cell(value)} | |`,
  ),
  '',
];

const outDir = join(root, 'docs', 'i18n-review');
mkdirSync(outDir, { recursive: true });
writeFileSync(join(outDir, `${lang}.md`), lines.join('\n'));
console.log(`Wrote docs/i18n-review/${lang}.md (${target.length} strings)`);
